// Counter actions
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const CLEAR_COUNTER = 'CLEAR_COUNTER';

//Shopping Cart
export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const SET_SHOPPING_LIST = 'SET_SHOPPING_LIST';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_TO_SELECTED_LIST = 'ADD_TO_SELECTED_LIST';
export const REMOVE_FROM_SELECTED_LIST = 'REMOVE_FROM_SELECTED_LIST';
export const UPDATE_SELECTED_ITEM = 'UPDATE_SELECTED_ITEM';

//Weather App
export const SET_5DAY_FORECAST = 'SET_5DAY_FORECAST';
export const SET_COORDINATES = 'SET_COORDINATES';
export const SET_CURRENT_WEATHER_INFO = 'SET_CURRENT_WEATHER_INFO';
export const SET_LIVE_WEATHER_INFO = 'SET_LIVE_WEATHER_INFO';
export const SET_16DAY_FORECAST = 'SET_16DAY_FORECAST';
export const SET_HOURLY_FORECAST = 'SET_HOURLY_FORECAST';
export const SET_WEATHER_ALERTS = 'SET_WEATHER_ALERTS';

//General
export const SET_THEME_COLOR = 'SET_THEME_COLOR';
export const START_LOADER = 'START_LOADER';
export const STOP_LOADER = 'STOP_LOADER';
