// Counter actions
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const CLEAR_COUNTER = 'CLEAR_COUNTER';

//Shopping Cart
export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const SET_SHOPPING_LIST = 'SET_SHOPPING_LIST';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_TO_SELECTED_LIST = 'ADD_TO_SELECTED_LIST';
export const REMOVE_FROM_SELECTED_LIST = 'REMOVE_FROM_SELECTED_LIST';
export const UPDATE_SELECTED_ITEM = 'UPDATE_SELECTED_ITEM';
